---
driver:
  name: vagrant
  vm_hostname: genkernel.ci.local
  use_sudo: false
  customize:
    memory: 512


provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  formula: genkernel
  log_level: info
  state_top:
    base:
      "*":
        - genkernel
  pillars:
    top.sls:
      base:
        "*":
          - genkernel
  grains:
    noservices: True

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
